
workflows:
  ios-build:
    name: Build iOS App
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Next.js static files
        script: |
          npm run build
      - name: Sync Capacitor project
        script: |
          npx capacitor sync ios
      - name: Install Pods
        script: |
          cd ios/App
          pod install
      - name: Build for Simulator
        script: |
          set -ex
          xcodebuild build -workspace ios/App/App.xcworkspace \
                           -scheme App \
                           -sdk iphonesimulator
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

