name: Build iOS IPA for Next.js Capacitor App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env
          echo "✅ .env file created successfully"

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Next.js app
        run: |
          npm run build

      - name: Sync Capacitor iOS platform
        run: |
          npx cap sync ios

      - name: Install CocoaPods dependencies
        run: |
          cd ios/App
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build iOS IPA
        run: |
          cd ios/App
          rm -rf build Payload
          
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -derivedDataPath Build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            build

          mkdir -p Payload
          
          if [ -d "Build/Build/Products/Release-iphoneos/App.app" ]; then
            cp -r Build/Build/Products/Release-iphoneos/App.app Payload/
          elif [ -d "Build/Products/Release-iphoneos/App.app" ]; then
            cp -r Build/Products/Release-iphoneos/App.app Payload/
          else
            echo "Searching for .app file..."
            find Build -name "*.app" -type d
            exit 1
          fi
          
          zip -qr build/App.ipa Payload
          rm -rf Payload
          
          echo "✅ IPA created successfully!"
          ls -la build/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: mzansi-shoppa-ios-ipa
          path: ios/App/build/App.ipa
          retention-days: 7

      - name: Build summary
        run: |
          echo "🎉 iOS build completed!"
          echo "📱 App: Mzansi Shoppa"
          echo "📦 Download the IPA from Artifacts section"
          echo "🔧 Use Sideloadly to install on iOS devices"